name: deploy
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: 'deploy'
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          PUBLIC_URL: /multiple-timer/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./dist

  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Setup pages
        uses: actions/configure-pages@v3

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v3
